API-10953 - Add WSDL for SvnTypeV2Service
department-of-veterans-affairs/lighthouse-benefits-gateway-services pull request #12
Opened 2021-11-01 21:48 UTC by bwisnaskas-va

Create new module bgs-client-svntype-v2 to support WSDL for SvnTypeV2Service. This was based on existing support for RatingWebService.

Also created module bgs-client-utility to hold common code use across WSDLs. Moved SoapHeaderUtils from bgs-client to bgs-client-utility

Jira: https://vajira.max.gov/browse/API-10953

2021-11-01 22:27 UTC, esubocz-va requested changes

2021-11-01 22:27 UTC, esubocz-va commented on bgs-model/src/main/resources/META-INF/wsdl/svn-type-v2/svnTypeV2Service.wsdl
> +<xsd:import namespace="http://gov.va.vba.benefits.awards/v2/services" schemaLocation="http://linktestbepbenefits.vba.va.gov:80/SvnTypeEJBV2/SvnTypeV2Service?xsd=1"/>
this `schemaLocation` causes failed local builds on non-GFEs. you will need to create an xsd file and embed it here rather than using a VPN required link. example: https://github.com/department-of-veterans-affairs/lighthouse-enterprise-military-information-service/blob/2898236e2603b467aea733d9dfde871b0426807f/emis-model/src/main/resources/META-INF/wsdl/v1/eMISVeteranStatusService.wsdl#L11

2021-11-01 22:27 UTC, esubocz-va commented on bgs-model/pom.xml
> +          <execution>
shouldn't need an second execution here, should be able to just specify multiple wsdl files from the same directory. example: https://github.com/department-of-veterans-affairs/lighthouse-enterprise-military-information-service/blob/2898236e2603b467aea733d9dfde871b0426807f/emis-model/pom.xml#L54

2021-11-01 22:41 UTC, bwisnaskas-va commented on bgs-model/pom.xml
> +          <execution>
Is there a way to control the packaging of the classes generated from the WSDLs if they are all in the same execution? The goal was to have the WSDLs all in separate packages, so using the <packageName> tag in the execution was how I was doing that. If no <packageName> is included, what determines the packaging?

2021-11-01 23:31 UTC, esubocz-va commented on bgs-model/pom.xml
> +          <execution>
the namespace determines the packaging, so this would go to `gov.va.vba.benefits.awards.v2.services` whereas the rating service will be packaged to `services.share.benefits.vba.va.gov`

2021-11-02 14:52 UTC, bwisnaskas-va commented on bgs-model/src/main/resources/META-INF/wsdl/svn-type-v2/svnTypeV2Service.wsdl
> +<xsd:import namespace="http://gov.va.vba.benefits.awards/v2/services" schemaLocation="http://linktestbepbenefits.vba.va.gov:80/SvnTypeEJBV2/SvnTypeV2Service?xsd=1"/>
I obtained a copy of the xsd from the linked schemaLocation and included it in the bgs-model resources folder with the wsdl.

2021-11-02 14:52 UTC, bwisnaskas-va commented on bgs-model/pom.xml
> +          <execution>
I removed the second execution and handled the multiple WSDLs in the single execution.  The namespace/package for the SvnTypeV2Service WSDL is awards.benefits.vba.va.gov.v2.services.

2021-11-03 20:43 UTC, esubocz-va approved these changes

2021-11-03 20:54 UTC, merged