API-10953 - Add WSDL and client for ShareStandardDataWebService
department-of-veterans-affairs/lighthouse-benefits-gateway-services pull request #13
Opened 2021-11-03 22:04 UTC by bwisnaskas-va

Create new module bgs-client-sharestandarddata to support WSDL for ShareStandardDataWebService.

2021-11-03 22:06 UTC, esubocz-va commented
build failed.

2021-11-03 22:25 UTC, esubocz-va requested changes
build failed.

2021-11-04 00:23 UTC, esubocz-va commented on bgs-client-sharestandarddata/pom.xml
> +  <version>2.0.6-SNAPSHOT</version>
this version doesn't match rest of project

2021-11-04 12:07 UTC, bwisnaskas-va commented on bgs-client-sharestandarddata/pom.xml
> +  <version>2.0.6-SNAPSHOT</version>
Thank you. I have fixed that and the build passed. I made these changes in parallel with the last WSDL/client update when the versions were all 2.0.6-SNAPSHOT. When the last PR was merged, the versions bumped to 2.0.7-SNAPSHOT, but I missed updating it here before committing for this PR. I now know to keep this in mind for the additional WSDL/client work to follow.

2021-11-04 16:00 UTC, esubocz-va commented on bgs-client-sharestandarddata/pom.xml
> +  </properties>
I missed this in the last PR, but this property isn't necessary. it is only necessary in the utility module because the header builder method is the only thing tested in this repo.

2021-11-04 16:16 UTC, bwisnaskas-va commented on bgs-client-sharestandarddata/pom.xml
> +  </properties>
I removed the property tag from the pom. I can remove it from the last client within the PR for the next one. Thank you.

2021-11-04 16:50 UTC, esubocz-va commented on bgs-client-sharestandarddata/src/main/java/gov/va/api/lighthouse/bgs/SoapBgsShareStandardDataClient.java
> +    try {
this code is repeated 3 times, recommend pulling out into a method

2021-11-04 16:50 UTC, esubocz-va commented on bgs-client-sharestandarddata/src/main/java/gov/va/api/lighthouse/bgs/SoapBgsShareStandardDataClient.java
> +                  "",
are these intentionally blank?

2021-11-05 17:14 UTC, esubocz-va commented on bgs-client-utility/src/main/java/gov/va/api/lighthouse/bgs/SoapHeaderUtils.java
> +  public static final String BGS_EXTERNAL_UID_KEY = "lighthouse";
I don't think this is a good place for this variable. I would recommend adding an extern uid field in your configuration file and setting this as a default there.

2021-11-05 17:15 UTC, esubocz-va commented on bgs-client-sharestandarddata/src/main/java/gov/va/api/lighthouse/bgs/BgsConfigShareStandardData.java
> +  String keystorePath;
you can use sslEnabled as an example for the external uid field to be added.

2021-11-05 17:38 UTC, bwisnaskas-va commented on bgs-client-utility/src/main/java/gov/va/api/lighthouse/bgs/SoapHeaderUtils.java
> +  public static final String BGS_EXTERNAL_UID_KEY = "lighthouse";
Ok. I have moved that into the configuration class as two separate fields, both defaulting to the same value.

2021-11-05 17:39 UTC, bwisnaskas-va commented on bgs-client-sharestandarddata/src/main/java/gov/va/api/lighthouse/bgs/BgsConfigShareStandardData.java
> +  String keystorePath;
Thanks for the example. I have added the fields here.

2021-11-05 17:49 UTC, esubocz-va approved these changes
Changes LGTM.

2021-11-05 18:03 UTC, merged